"""empty message

Revision ID: 312fa08bce34
Revises: c982688b03bb
Create Date: 2020-05-28 13:20:48.651543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '312fa08bce34'
down_revision = 'c982688b03bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'todo_list', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo_list', type_='unique')
    # ### end Alembic commands ###
